
Regression Model-Treebased
=================================================================
##Treebased method for predictive modelling


### Basic Settings  
```{r}

echo = TRUE
setwd("c:/Users/jasmine.qi/Documents/Regression")

library(ggplot2)
library(lattice)
library(caret)
library(rpart)
library(rpart.plot)
library(miscTools)
library(rattle)
library(RSNNS)
library(nnet)
library(neuralnet)
library(MARSS)
library(earth)
library(tidyr)
library(e1071)
library(Rcmdr)
library(randomForest)

```

```{r}
total= read.csv("Derivedata.csv")
total=total[!(is.na(total$Classifier)),]

##randomsize 70% of row of data as training set and test set
#set.seed(15)

indexes = sample(1:nrow(total), size= 0.7*nrow(total))
train = total[indexes, ]
test = total[-indexes, ]

nrow(train)
nrow(test)

## plot train and test dataset

group <- rep(NA,842)
group <- ifelse(seq(1,842) %in% indexes,"Train","Test")
df <- data.frame(LoanID=total$LoanID,Loanscores=total$Loanscore)

# ...and plot it
ggplot(df,aes(x = LoanID,y = Loanscores, color = group)) + geom_point() +
  scale_color_discrete(name="") + theme(legend.position="top")

```

## Non Tree-based Model
```{r}

##Multilinear regression

  formula=Loanscore ~ Absorption.Rate...prior.4.6.months. + 
  Absorption.Rate...prior.7.12.months. + 
  Absorption.Rate...prior.current.3.months. + Appraisal.Monthly.Rent + 
  Appraisal.price + Assignment.Type + Bankrupcy + Baths + Bedrooms + 
  Borrower.Age.Group + Borrower.Rent + Built.up + Charge.offs + 
  Closed.Past.Auto.Late + Closed.Past.Education.Late + 
  Closed.Past.Installment.Late + Closed.Past.Mortgage.Late + 
  Closed.Revolving.Late + Collections + Comparable.properties.lower.price + 
  Comparable.properties.upper.price + Comparable.sale.lower.price.range + 
  Comparable.sale.upper.price.range + Condition + Credit.Score  + 
  Current.Rent + Debt.High.Credit.... + Demand.Supply + 
  distancemiles + DOM + Expected.cost.to.Rehab63 + Expected.flip.price + 
  Foreclosure + Foreclosure.sales + 
  Full.or.Part.Time.investor + Growth + Indicated.Value.by.Cost.Approach + 
  Indicated.Value.by.Income.Approach + Interest.Rate + Lending.Value + 
  Loan.Purpose + Loan.Term + Loan.Type + Location + LTV + Male.Female + 
  Marketing.Time + Median.Comparable.List.Price.prior.4.6.months. + 
  Median.Comparable.List.Price.prior.7.12.months. + 
  Median.Comparable.List.Price.prior.current.3.months. + 
  median.Comparable.listings.Days.on.Market.prior.4.6.months. + 
  median.Comparable.listings.Days.on.Market.prior.7.12.months. + 
  median.Comparable.listings.Days.on.Market.prior.current.3.months. + 
  Median.Comparable.Sale.Price..prior.4.6.months. + 
  Median.Comparable.Sale.Price..prior.7.12.months. + 
  Median.Comparable.Sale.Price..prior.current.3.months. + 
  Median.Comparable.sales.Days.on.market.prior.4.6.months. + 
  Median.Comparable.sales.Days.on.market.prior.7.12.months. + 
  Median.Comparable.sales.Days.on.market.prior.current.3.months. + 
  Median.Sale.Price.a.s..of.List.Price.prior.4.6.months. + 
  Median.Sale.Price.a.s..of.List.Price.prior.7.12.months. + 
  Median.Sale.Price.a.s..of.List.Price.prior.current.3.months. + 
  Months.of.Housing.Supply.prior.4.6.months. + 
  Months.of.Housing.Supply.prior.7.12.months. + 
  Months.of.Housing.Supply.prior.current.3.months. + Occupant + 
  Open.Current.Auto.Late + Open.Current.Education.Late + 
  Open.Current.Installment.Late + Open.Current.Mortgage.Late + 
  Open.Current.Revolving.Late  + Origination.UPB + 
  OrigTransdays + Price.of.Prior.Sale.Transfer+ 
  Property.Values + Rent.Own + Repeat + Rooms + Sale.Price + Size + 
  Square.feet.of.gross.living.area  + 
  Subject..PropertyState + Total...of.Comarable.Sales...prior.4.6.months. + 
  Total...of.Comarable.Sales...prior.7.12.months. + 
  Total...of.Comarable.Sales...prior.current.3.months. + 
  Total...of.Comparable.Active.listings.prior.4.6.months. + 
  Total...of.Comparable.Active.listings.prior.7.12.months. + 
  Total...of.Comparable.Active.listings.prior.current.3.months. + Type + 
  Units + VFS.Internal.Value + WLV + X..of.comarable.properties + 
  X..of.comparable.sales + X..of.home.purchased.in.last.3.years + 
  X..of.Properties.currently.owned + X..of.years.investing +Yearbuilt+MR.UPB+MR.LV +MR.VFS+MR.APP+MR.MCSP+LV.VFS+APP.VFS+UPB.VFS





```

##New LM model after stepwise
```{r}
linreg = lm(formula, data=train)

#summary(linreg)
```

```{r,  include=FALSE, cache=FALSE}

linreg.new= stepwise(linreg, direction = "backward", criterion = "AIC")
```
```{r}
summary(linreg.new)

#Apply LM model to test data 

test_pred_lm = predict(linreg.new, newdata=test)

# Evaluate the accuracy
RMSE_linreg = sqrt(mean(test_pred_lm-test$Loanscore)^2)
RMSE_linreg

MAE_linreg = mean(abs(test_pred_lm-test$Loanscore))
MAE_linreg

```

## Set Tree based methods
```{r}

##grow tree
train_tree = rpart(formula, data= train)

train_tree$cptable
plotcp(train_tree)

## create additional plots 

par(mfrow=c(1,2))
rsq.rpart(train_tree)

```

```{r}

##plot tree of trainig model

fancyRpartPlot(train_tree, cex=0.5,main= "Tree of CART ", sub="" )


```


```{r}

##predict using decision Tree

test_pred = predict(train_tree, newdata= test)

##check performance of tree model
train_tree_r2=rSquared(test$Loanscore, test$Loanscore-test_pred)
MSE_tree = mean(test$Loanscore - test_pred)
train_tree_r2
MSE_tree

RMSE_tree = sqrt(mean(test_pred-test$Loanscore)^2)
RMSE_tree

MAE_tree = mean(abs(test_pred-test$Loanscore))
MAE_tree

```
###prune the tree

```{r}

opt = train_tree$cptable[which.min(train_tree$cptable[, "xerror"]),1]
ptrain_tree = prune(train_tree, cp=opt)


fancyRpartPlot(ptrain_tree, cex=0.7,main= "Pruned Tree", sub="" )



#predict using pruning tree

ptest_pred=predict(ptrain_tree, test)

RMSE_ptree = sqrt(mean(ptest_pred-test$Loanscore)^2)
RMSE_ptree

MAE_ptree =mean(abs(ptest_pred-test$Loanscore))
MAE_ptree

```
###Random Forest method

```{r}

#set.seed(15)

train_rf=randomForest(formula, data=train, na.action=na.omit, ntree=850,mtry=8, proximity=T)
train_rf
plot(train_rf)

##importance of each variables
imp =as.data.frame(sort(importance(train_rf)[,1],decreasing = TRUE),optional = T)
names(imp) = "%Inc MSE"

imp

## prediction test data
test_pred3= predict(train_rf, newdata=test)

## R^2 and MSE
train_r2= rSquared(test$Loanscore, test$Loanscore-test_pred3)
train_r2

MSE = mean(test$Loanscore - test_pred3)
MSE

RMSE_rf= sqrt(mean(test_pred3-test$Loanscore)^2)
RMSE_rf

MAE_rf = mean(abs(test_pred3-test$Loanscore))
MAE_rf

##plot importance variables
varImpPlot(train_rf, cex=0.7, main="Linear Regresssion Model Top Importance Variables")


```

## Other Regression Model

### Load Clean Data
```{r}


total= read.csv("datawocolin.csv") #read data file which has transformed, and encoding categrecals
#encoding  N = -1 Y = 1  
total$LoanID=NULL
total$X = NULL

dim(total)


indexes = sample(1:nrow(total), size= 0.7*nrow(total))

train = total[indexes, ]
dim(train)
myvars =names(train) %in% "Loanscore"
trainX= train[!myvars]
trainY =train$Loanscore#        

test = total[-indexes, ]
myvarsTest = names(test) %in% "Loanscore"
testX= test[!myvarsTest]
testY = test$Loanscore
```

###NW
```{r}
nnetTune = train(trainX, trainY,
                  method = "nnet",
                trainControl=trainControl(method="cv"),
                  linout = TRUE,
                  trace = FALSE)


plot(varImp(nnetTune), top=15, main="Neural Work Model Top Importance Variables")


test_nnet = predict(nnetTune, test)

RMSE_nnet=sqrt(mean(test_nnet-test$Loanscore)^2)
RMSE_nnet

MAE_nnet=mean(abs(test_nnet-test$Loanscore))
MAE_nnet

```
###MARS 

```{r}
train_mars = earth(trainX, trainY)
train_mars



test_mars=predict(train_mars, test)

RMSE_mars=sqrt(mean(test_mars-test$Loanscore)^2)
RMSE_mars

MAE_mars=mean(abs(test_mars-test$Loanscore))
MAE_mars

```




###kNN
```{r}
# Remove a few sparse and unbalanced fingerprints first
knnDescr = trainX[, -nearZeroVar(trainX)] 
knnTune = train(knnDescr,
                trainY,
                method = "knn",
                tuneGrid = data.frame(.k = 1:20),
                trControl = trainControl(method = "cv"))

plot(varImp(knnTune), top=15, main="K Nearest Neiborhood Model Top Importance Variables")


test_knn=predict.train(knnTune, testX[, -nearZeroVar(trainX)])

RMSE_knn=sqrt(mean(test_knn-test$Loanscore)^2)
RMSE_knn

MAE_knn=mean(abs(test_knn-test$Loanscore))
MAE_knn

``` 


##Comparison of performance of models

```{r}
##Accuracy 
accuracy = data.frame(Method = c("Linear Regression","Full tree","Pruned tree","Random forest", "Neural Work", "MARS", "KNN"),
                         RMSE   = c(RMSE_linreg,RMSE_tree,RMSE_ptree,RMSE_rf, RMSE_nnet, RMSE_mars, RMSE_knn),
                         MAE    = c(MAE_linreg,MAE_tree,MAE_ptree,MAE_rf, MAE_nnet, MAE_mars, MAE_knn)) 

# Round it
accuracy$RMSE = round(accuracy$RMSE, 4)
accuracy$MAE = round(accuracy$MAE, 4)

accuracy


# predictions comparison

predictions_comp = data.frame(actual = test$Loanscore,
                              linear.regression = test_pred_lm,
                              full.tree = test_pred,
                              pruned.tree = ptest_pred,
                              random.forest = test_pred3,
                              Neural.Work = test_nnet, 
                              MARS= test_mars,
                              KNN = test_knn)

colnames(predictions_comp)=c("actual", "linear.regression", " full.tree ", "pruned.tree", "random.forest", "Neural.Work", "MARS","KNN")
head(predictions_comp)

#reshape dataset


all.predictions = gather(predictions_comp,key = model,value = predictions,2:8)

head(all.predictions)
tail(all.predictions)


#plot performence of prediciton model with actual data

ggplot(data = all.predictions,aes(x = actual, y = predictions)) + 
  geom_point(colour = "blue") + 
  geom_abline(intercept = 0, slope = 1, colour = "red") +
  geom_vline(xintercept = 400, colour = "green", linetype = "dashed") +
  facet_wrap(~ model,ncol = 2) + 
  coord_cartesian(xlim = c(120,1100),ylim = c(120,1100)) +
  ggtitle("Predicted vs. Actual, by model")

```
